### ISSUE TITLE
Additional extra resources created after upgrading from 1.12 to 1.21.1

### ISSUE THREAD

**Issue by marknesterovych** [k8ssandra/k8ssandra-operator#1491]
**What did you do?**
I had a cluster created with following StatefulSets created: cassandra-us-east-1-us-east-1a-sts-0 cassandra-us-east-1-us-east-1b-sts-0 cassandra-us-east-1-us-east-1c-sts-0
After upgrading the operator to version 1.21.1 3 new additional StatefulSets were created with following names: cassandra--us-east-1a-sts-0 cassandra--us-east-1b-sts-0 cassandra--us-east-1c-sts-0.
They are trying to sync data from old ones.
K8ssandraCluster.status.nodeStatuses now shows 6 nodes instead of 3.
Looks like in StatefulSet name generation there is an issue which forget to insert datacenter name.

datacenterName attribute set to empty string, so name should be taken from metadata.name. But looks like it fails.

**Did you expect to see some different?**
Expected already created StatefulSets remains
**Environment**

* K8ssandra Operator version: 1.21.1
* Kubernetes version information:

    `kubectl version`
  Client Version: v1.32.1
  Kustomize Version: v5.5.0
  Server Version: v1.32.0-eks-5ca49cb

* Kubernetes cluster kind:

    kops

**Comment by iAlex97** [comment]
I was just about to post the same issue 😄 I suspect something might break during CRD upgrades and `k8ssandraclusters.k8ssandra.io` will have datacenterName set to empty string or null, possibly due to this https://github.com/k8ssandra/k8ssandra-operator/issues/1441

In my case, I upgraded the operator from `v1.20.1` to `v1.21.1`.

The only solution I could come up with was to delete `k8ssandraclusters.k8ssandra.io` and recreate it. This will**DELETE** all resources, including pods and PVCs (⚠  **MAKE SURE** that the backing class has `ReclaimPolicy: Retain` otherwise you will probably lose your data ⚠ ) 
Afterwards, I have updated the `K8ssandraCluster` yaml to include datacenterName just to be on the safe side, like so:
```yaml
apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
metadata:
  name: prod
  namespace: k8ssandra-operator
spec:
...
  cassandra:
    datacenterName: fsn1

    datacenters:
      - metadata:
          name: fsn1
```

Applying this, recreated the pods with the proper name and created new PVCs, then it was a laborious process to update `Released` PVs fields. Basically this:

```
kubectl -n k8ssandra-operator get pvc server-data-prod-fsn1-rack3-sts-16 -o yaml
# copy metadata.resourceVersion and metadata.uid
kubectl get pv | grep Released | grep topolvm-cassandra | grep rack3-sts-16
# edit PV spec.claimRef to "pair" with new PVC (fields to be upgraded are spec.claimRef.uid and spec.claimRef.uid
kubectl edit pv ...
```

Unlike some online guides who suggest deleting the PV `claimRef`, this will allow you to bind the exact pod in a StatefulSet to its previous volume which seems quite importat (I don't even want to know what would happen if Cassandra hosts would start and mess up the token ranges)

Finally, as the entire cluster was down, you have to trick the operator into selecting a seed node. In my case I updated and reapplied `K8ssandraCluster` `spec.cassandra.datacenters[].stopped` to `true` and then `false` in order to let the operator start the cluster.

This, however only selected the first node in the first rack as seed node and none of the other nodes tried to start - I think the operator still was stuck and wasn't commanding the management-api to start the cassandra process. You can, however start the cassandra process manually by exec-ing into a pod and I suggest the first node in each un-started rack.

```
kubectl -n k8ssandra-operator exec -ti prod-fsn1-rack3-sts-0 -c cassandra -- /bin/bash

[cassandra@prod-fsn1-rack3-sts-11 /]$ export JAVA_VERSION=11
[cassandra@prod-fsn1-rack3-sts-11 /]$ source /opt/cassandra/conf/cassandra-env.sh
[cassandra@prod-fsn1-rack3-sts-11 /]$ /opt/cassandra/bin/cassandra -Dcassandra.server_process -Dcassandra.skip_default_role_setup=true -Ddb.unix_socket_file=/tmp/cassandra.sock
```

After a downtime of 4-5 hours, this got the operator to start the remaining instances one by one. The last remaining step is to delete the pods where you manually started the cassandra process, as the operator still thinks it could not start that node (my `K8ssandraCluster` had condition Ready: false). Deleting those instances got the status Ready: true and everything was back to normal.

I think the users should be warned before attempting to upgrade the operator to the last version as this could lead to downtime and even worse, data loss.

**Comment by marknesterovych** [comment]
Can not afford downtime. Is there any annotation or something to move StatefulSet out of control of the operator ?

**Comment by vigneshkumarak** [comment]
I am trying to upgrade from `1.20.1` to `1.21.1` 

This works for me 
Before Rollback we need to remove the `datacenterName` from the `cassandradatacenter`

`kubectl patch -n cassandra cassandradatacenter dc1 --type=merge --subresource status --patch 'status: {datacenterName: ~}'`

**Comment by mikkotimoharju** [comment]
We encountered this same problem when upgrading k8ssandra-operator from 1.20.2 to 1.21.1. The reason why this happens is the empty string "" datacenterName  definition in cassandradatacenter resource, e.g.
```
status:
  datacenterName: ""
```

Why this has happened is not known, might have been a bug in k8ssandra-operator at some point. The datacenterName cannot be changed after it is set, even if it is an empty string.

There is an already fixed issue about this in cass-operator https://github.com/k8ssandra/cass-operator/issues/751 but this is not yet included in the latest k8ssadra-operator helm chart (atm 1.21.1). Forcing newer version of cass-operator might prevent this problem when updating k8ssandra-operator.

**Comment by burmanm** [comment]
> The existing reaper will use the empty string when connecting to k8ssandra service, e.g. the name will be for example k8ssandra--service. This will cause the reaper to fail and crashloop. In order to circumvent this problem, we had to create a Service alias (e.g. Service of type ExternalName) with that name and pointing to the actual k8ssandra service.

This required a bump in the k8ssandra-operator's go-dependency, but is already fixed in the main branch (PR #1500). Should be available in the next version.

**Comment by mikkotimoharju** [comment]
> > The existing reaper will use the empty string when connecting to k8ssandra service, e.g. the name will be for example k8ssandra--service. This will cause the reaper to fail and crashloop. In order to circumvent this problem, we had to create a Service alias (e.g. Service of type ExternalName) with that name and pointing to the actual k8ssandra service.
> 
> This required a bump in the k8ssandra-operator's go-dependency, but is already fixed in the main branch (PR [#1500](https://github.com/k8ssandra/k8ssandra-operator/pull/1500)). Should be available in the next version.

Bumping the cass-operator dependency does not solve the problem with the cassandra reaper. It will still use the empty string for datacenter name when creating the reaper. To be more specific, the environment variable `REAPER_CASS_CONTACT_POINTS` will be in the format <deployment name>-<empty string>-service. The reaper deployment can be manually edited and the `REAPER_CASS_CONTACT_POINTS` variable changed, but whenever the operator updates the reaper deployment, the `REAPER_CASS_CONTACT_POINTS` will be with the empty string.

**Comment by burmanm** [comment]
The ``REAPER_CASS_CONTACT_POINTS`` is created by the following code: ``Value: fmt.Sprintf("[%s]", dc.GetDatacenterServiceName()),``.

In this case, the bump of dependency changes the behavior of ``GetDatacenterServiceName()`` to ignore the empty DatacenterName so it will use the dc.Name instead. So instead of ``k8ssandra--service`` it would become ``k8ssandra-dc1-service`` or similar.

**Comment by ptrekelsseg** [comment]
I noticed version 1.21.2 is released now. But it still contains a dependency to the 0.55.0 / 1.23.0 version of the cass-operator, so not including the fix mentioned here? Is there a technical reason not to jump to 0.55.2 / 1.23.2 cass-operator?
